Repository rawheel/MyUnfollowers-App, pull requests merged in 2022-10, with the labels that each got.

#48 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted

#60 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#59 Shahzaib details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#56 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#55 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#54 update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#18 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#52 Added my connection details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#53 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#50 added my contributions
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#49 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#47 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#46 added my contact details
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#45 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#44 Added my connection details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#43 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#42 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#41 Update Details By Talha442
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#40 Update Details.txt by Aashir
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#39 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#38 Update details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#37 updated details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#36 Added Sohaib detail
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#35 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#33 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#32 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#31 Update Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#30 Added personal details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#29 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#28 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#26 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#25 Update Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#23 Update Details
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#22 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#21 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#19 Added AbdulSamad in Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#61 Update Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#62 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#63 Update Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#64 Update Details.txt
  Details.txt
Labels: hacktoberfest-accepted, hacktoberfest

#65 Update Details.txt
  Details.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
